apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-billingapp-configmap
data:
  port: "7080"
#Obtener el nombre del host con el comando 
#kubectl describe service [nombre del servicio]
  db_host: "192.168.165.250:5432"
  database: billingapp_db
#  username: postgres
#  password: sasa
#  usuario_url: "msvc-usuarios:8001"