apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-billingapp-configmap
data:
  port: "7080"
  db_host: "postgres16-service:5432"
  database: billingapp_db
#  username: postgres
#  password: sasa
#  usuario_url: "msvc-usuarios:8001"
