apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres16-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres16
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
            #read envars from secret file
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-script-configmap
